intra/Models/MiPerfilAvatars.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using intra;
using System.ComponentModel.DataAnnotations.Schema;

namespace intra.Models
{
    public class MiPerfilAvatars
    {
        [Key]
        public int id { get; set; }
        public string codigoEmpleado { get; set; }
        public string avatar { get; set; }

    }
}

intra/Controllers/MiPerfilAvatarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using intra;
using intra.Models;
using System.IO;

namespace intra.Controllers
{
    public class MiPerfilAvatarsController : Controller
    {
        private dbIntranet db = new dbIntranet();

        // GET: MiPerfilAvatars
        [CustomAuthorize]
        public ActionResult Index()
        {

            return View();
        }

        // GET: MiPerfilAvatars/Details/5
        [CustomAuthorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MiPerfilAvatars miPerfilAvatars = db.MiPerfilAvatars.Find(id);
            if (miPerfilAvatars == null)
            {
                return HttpNotFound();
            }
            return View(miPerfilAvatars);
        }

        // GET: MiPerfilAvatars/Create
        [CustomAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: MiPerfilAvatars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize]
        public ActionResult Create(HttpPostedFileBase file)
        {
            MiPerfilAvatars avatar = new MiPerfilAvatars();

            //ruta de para guardar Imagenes
            string ruta = HttpRuntime.AppDomainAppPath + "Content\\images\\userImages";
            string EmpId = @Session["empleadoId"].ToString();

           

            if (file != null && file.ContentLength > 0)
            {
                string Ext = Path.GetExtension(file.FileName);
                string Archivo = file.FileName.Replace(file.FileName, EmpId + Ext);              
                string path = Path.Combine(ruta, Archivo);

                if (EmpId != "" && Ext == ".jpeg" || Ext == ".jpg" || Ext == ".png" || Ext == ".JPEG" ||
                    Ext == ".JPG" || Ext == ".PNG")
                {

                    file.SaveAs(path);
                    avatar.avatar = HttpRuntime.AppDomainAppVirtualPath + "/Content/images/userImages/" + Archivo;
                    avatar.codigoEmpleado = EmpId;
                }
                else
                {
                    ViewBag.MsjError = "Solo Se Admiten Imagenes en Formato JPEG & PNG";
                    return View("Create", avatar);
                }
            }
            else
            {
                //Imagen por Defecto en caso de no subir ninguna
                //avatar.avatar = string.Concat(ruta, "user.png");
                ViewBag.MsjError = "Debe Cargar Una Imagen";
                return View("Create", avatar);
            }

            if (ModelState.IsValid)
            {
                db.MiPerfilAvatars.Add(avatar);
                db.SaveChanges();

                HttpContext.Session["avatar"] = avatar.avatar;

                string empId = HttpContext.Session["empleadoId"].ToString();
                RegisterLogs rl = new RegisterLogs(empId, "Subio una imagen a su perfil");
                return RedirectToAction("Index","Home");
            }

            
            return View("Create", avatar);                
            
        }

        // GET: MiPerfilAvatars/Edit/5
        [CustomAuthorize]
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MiPerfilAvatars miPerfilAvatars = db.MiPerfilAvatars.Where(x=>x.codigoEmpleado==id).FirstOrDefault();
            if (miPerfilAvatars == null)
            {
                return HttpNotFound();
            }
            return View(miPerfilAvatars);
        }

        // POST: MiPerfilAvatars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize]
        public ActionResult Edit(HttpPostedFileBase file, FormCollection vd)
        {
            //ruta de para guardar Imagenes

            string ruta = HttpRuntime.AppDomainAppPath + "Content\\images\\userImages";
            string EmpId = @Session["empleadoId"].ToString();

            MiPerfilAvatars avatar = db.MiPerfilAvatars.Where(x => x.codigoEmpleado == EmpId).FirstOrDefault();
            
            if (file != null && file.ContentLength > 0)
            {
                string Ext = Path.GetExtension(file.FileName);
                string Archivo = file.FileName.Replace(file.FileName, EmpId + Ext);
                string path = Path.Combine(ruta, Archivo);

                if (EmpId != "" && Ext == ".jpeg" || Ext == ".jpg" || Ext == ".png")
                {
                    FileInfo fi = new FileInfo(avatar.avatar);

                    //var server_path = Server.MapPath(ruta);
                    var server_path = ruta;

                    try
                    {
                        System.IO.File.Delete(Path.Combine(server_path, fi.Name));

                        file.SaveAs(path);
                        avatar.avatar = HttpRuntime.AppDomainAppVirtualPath + "/Content/images/userImages/" + Archivo;
                        avatar.codigoEmpleado = EmpId;
                    }catch(Exception)
                    {
                        return RedirectToAction("Create");
                    }
                }
                else
                {
                    ViewBag.MsjError = "Solo Se Admiten Imagenes en Formato JPEG & PNG";
                    return View("Edit", avatar);
                }
            }
            else
            {
                //Imagen por Defecto en caso de no subir ninguna
                //avatar.avatar = string.Concat(ruta, "user.png");
                ViewBag.MsjError = "Debe Cargar Una Imagen";
                return View("Edit", avatar);
            }

            if (ModelState.IsValid)
            {              
                db.Entry(avatar).State = EntityState.Modified;
                db.SaveChanges();

                HttpContext.Session["avatar"] = avatar.avatar;

                string empId = HttpContext.Session["empleadoId"].ToString();
                RegisterLogs rl = new RegisterLogs(empId, "Cambio su imagen de perfil");

                return RedirectToAction("Index", "MiPerfil");
            }


            return View("Edit", avatar);
        }

        // GET: MiPerfilAvatars/Delete/5
        [CustomAuthorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MiPerfilAvatars miPerfilAvatars = db.MiPerfilAvatars.Find(id);
            if (miPerfilAvatars == null)
            {
                return HttpNotFound();
            }
            return View(miPerfilAvatars);
        }

        // POST: MiPerfilAvatars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [CustomAuthorize]
        public ActionResult DeleteConfirmed(int id)
        {
            MiPerfilAvatars miPerfilAvatars = db.MiPerfilAvatars.Find(id);
            db.MiPerfilAvatars.Remove(miPerfilAvatars);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

intra/Views/MiPerfilAvatars/Create.cshtml
@model intra.Models.MiPerfilAvatars

@{
    ViewBag.Title = "Cambiar Imagen";
    Layout = "~/Views/intraMaster.cshtml";
}
<link href="~/Content/css/jquery-te-1.4.0.css" rel="stylesheet" />
<script src="~/scripts/jquery-te-1.4.0.min.js"></script>
<script src="~/scripts/jquery-te-1.4.0.js"></script>
<script src="~/scripts/jquery.validate.js"></script>

<style>
    .cerrar{display:none;}
</style>


@using (Html.BeginForm("create", "MiPerfilAvatars", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Código", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Session["empleadoId"].ToString()
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Cargar Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" class="form-control" />
            </div>
        </div>
    </div>

    if (!string.IsNullOrEmpty(ViewBag.MsjError))
    {
        <div class="alert alert-danger">
            <strong> @ViewBag.MsjError</strong>
        </div>
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" name="Guardar" value="Guardar" class="buttonAceptar" />
        </div>
    </div>
}


<div>
    @Html.ActionLink("Volver", "Index","MiPerfil")
</div>


<script>
	$('.jqte-test').jqte();

	// settings of status
	var jqteStatus = true;
	$(".status").click(function()
	{
		jqteStatus = jqteStatus ? false : true;
		$('.jqte-test').jqte({"status" : jqteStatus})
	});

</script>

<script>
$().ready(function() {
        // valida Formulario
        $("form").validate({
            rules: {
                avatar: "required",

                    },
            messages: {
                avatar: "El nombre es Requerido",
                      }
        })

});

</script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

intra/Views/MiPerfilAvatars/Delete.cshtml
@model intra.Models.MiPerfilAvatars

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/intraMaster.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MiPerfilAvatars</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

intra/Views/MiPerfilAvatars/Details.cshtml
@model intra.Models.MiPerfilAvatars

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/intraMaster.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MiPerfilAvatars</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

intra/Views/MiPerfilAvatars/Edit.cshtml
@model intra.Models.MiPerfilAvatars

@{
    ViewBag.Title = "Editar Imagen";
    Layout = "~/Views/intraMaster.cshtml";
}
<link href="~/Content/css/jquery-te-1.4.0.css" rel="stylesheet" />
<script src="~/scripts/jquery-te-1.4.0.min.js"></script>
<script src="~/scripts/jquery-te-1.4.0.js"></script>
<script src="~/scripts/jquery.validate.js"></script>



@using (Html.BeginForm("edit", "MiPerfilAvatars", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Código", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Session["empleadoId"].ToString()
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Cargar Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" class="form-control" />
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="buttonAceptar" />
        </div>
    </div>
}


<div>
    @Html.ActionLink("Volver", "Index","MiPerfil")
</div>


<script>
	$('.jqte-test').jqte();

	// settings of status
	var jqteStatus = true;
	$(".status").click(function()
	{
		jqteStatus = jqteStatus ? false : true;
		$('.jqte-test').jqte({"status" : jqteStatus})
	});

</script>

<script>
$().ready(function() {
        // valida Formulario
        $("form").validate({
            rules: {
                avatar: "required",

                    },
            messages: {
                avatar: "El nombre es Requerido",
                      }
        })

});

</script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

intra/Views/MiPerfilAvatars/Index.cshtml
@model IEnumerable<intra.Models.MiPerfilAvatars>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/intraMaster.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.avatar)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.avatar)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>