intra/Models/Tutoriales.cs
namespace intra
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Web;
    public partial class Tutoriales
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int TutorialId { get; set; }
        
        public string TutorialNombre { get; set; }
      
        public string TutorialUsuario { get; set; }
       
        public DateTime FechaCreacion { get; set; }
      
        public string TutorialUrl { get; set; }
        public string Portada { get; set; }
        public bool Estado { get; set; }

    }
}

intra/Controllers/TutorialesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using intra;
using System.IO;
using PagedList;
using System.Web.Hosting;
using intra.Controllers;



namespace intra.Controllers
{
    public class TutorialesController : Controller
    {
        private dbIntranet db = new dbIntranet();

        //[CustomAuthorize]
        // GET: Tutoriales
        public ActionResult Index()
        {
            string EmpId = string.Empty;

            try
            {
                if (!string.IsNullOrEmpty(HttpContext.Session["empleadoId"].ToString()))
                {
                    EmpId = HttpContext.Session["empleadoId"].ToString();
                }
                else
                {
                    EmpId = "public_user";
                }
            }
            catch (Exception)
            {
                EmpId = "public_user";
            }

            ViewBag.access = EmpId;

            //string empId = HttpContext.Session["empleadoId"].ToString();
            RegisterLogs rl = new RegisterLogs(EmpId, "Ingreso al Modulo de tutoriales)");
            return View(db.Tutoriales.Where(x=> x.Estado == true).ToList());
        }

        //[CustomAuthorize]
        // GET: Tutoriales/Details/5
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (HttpContext.Session["empleadoId"] == null) { return RedirectToAction("Index", "login", new { url = Request.Url.AbsoluteUri }); }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string EmpId = string.Empty;

            try
            {
                if (!string.IsNullOrEmpty(HttpContext.Session["empleadoId"].ToString()))
                {
                    EmpId = HttpContext.Session["empleadoId"].ToString();
                }
                else
                {
                    EmpId = "public_user";
                }
            }
            catch (Exception)
            {
                EmpId = "public_user";
            }
            
            Tutoriales tutoriales = db.Tutoriales.Find(id);

            ViewBag.access = EmpId;

            if (tutoriales == null)
            {
                return HttpNotFound();
            }

            return View(tutoriales);
        }

        public PartialViewResult vTutoriales()
        {
            return PartialView(db.Tutoriales.Where(x=> x.Estado == true).ToList());
        }

        [CustomAuthorize]
        // GET: Tutoriales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tutoriales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize]
        public ActionResult Create(HttpPostedFileBase file, FormCollection vd)
        {
            Tutoriales tutoriales = new Tutoriales();
            //ruta de para guardar videos

            string ruta = HttpRuntime.AppDomainAppVirtualPath + "/Content/videos/";
                //string.Concat(System.Configuration.ConfigurationManager.AppSettings["intra"], "Content/videos/");

              

            if (vd["Tutorial"] != "")
            {

                tutoriales.TutorialNombre = vd["Tutorial"];
                tutoriales.FechaCreacion = DateTime.Now;
                tutoriales.TutorialUsuario = HttpContext.Session["Usuario"].ToString();
                tutoriales.Estado = true;

                //tutoriales.video = vd["__contenido"];

                if (file != null && file.ContentLength > 0)
                {
                    string path = Path.Combine(Server.MapPath(ruta), Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    tutoriales.TutorialUrl = ruta + file.FileName;
                }
                else
                {
                    ViewBag.Tutoriales = "ok";
                    return View();
                }

                //if (file  != null && file.ContentLength > 0)
                //{
                //    string path = Path.Combine(Server.MapPath(ruta), Path.GetFileName(file.FileName));
                //    file.SaveAs(path);
                //    tutoriales.Portada = ruta + file.FileName;
                //}

                if (ModelState.IsValid)
                {
                    db.Tutoriales.Add(tutoriales);
                    db.SaveChanges();
                    string empId = HttpContext.Session["empleadoId"].ToString();
                    RegisterLogs rl = new RegisterLogs(empId, "Creo un Registro en el Modulo de tutoriales llamado ("+tutoriales.TutorialNombre+"))");
                    return RedirectToAction("Index");
                }


            }
            return View("Create", tutoriales);
        }


        [CustomAuthorize]
        // GET: Tutoriales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutoriales tutoriales = db.Tutoriales.Find(id);
            if (tutoriales == null)
            {
                return HttpNotFound();
            }
            return View(tutoriales);
        }

        // POST: Tutoriales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize]

        // POST: Tutorial/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        public ActionResult Edit(HttpPostedFileBase file, FormCollection vd)
        {
            //Tutoriales tutoriales = new Tutoriales();
            //Convertir para actualizar
            int tutorialId = Convert.ToInt32(vd["TutorialId"]);
            //ruta de para guardar videos
            string ruta = string.Concat(System.Configuration.ConfigurationManager.AppSettings["intranet"], "Content/videos/");
            Tutoriales tutoriales = db.Tutoriales.Find(tutorialId);
            tutoriales.TutorialNombre = vd["TutorialNombre"];
            tutoriales.FechaCreacion = tutoriales.FechaCreacion;
            tutoriales.TutorialUsuario = HttpContext.Session["Usuario"].ToString();

            //tutoriales.video = vd["__contenido"];

            if (file != null && file.ContentLength > 0)
            {
           
                string path = Path.Combine(Server.MapPath(ruta), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                tutoriales.TutorialUrl =  ruta + file.FileName;

            }
            else
            {
                tutoriales.TutorialUrl = tutoriales.TutorialUrl;
            }


            //if (file != null && file.ContentLength > 0)
            //{
            //    string path = Path.Combine(Server.MapPath(ruta), Path.GetFileName(file.FileName));
            //    file.SaveAs(path);
            //    tutoriales.Portada = ruta + file.FileName;
            //}

            if (ModelState.IsValid)
            {
                db.Entry(tutoriales).State = EntityState.Modified;
                db.SaveChanges();
         
                string empId = HttpContext.Session["empleadoId"].ToString();
                RegisterLogs rl = new RegisterLogs(empId, "Edito un Registro en el Modulo de tutoriales llamado (" + tutoriales.TutorialNombre + "))");
                return RedirectToAction("Index");
            }
            return View("Edit", tutoriales);
        }

        [CustomAuthorize]
        // GET: Tutoriales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tutoriales tutoriales = db.Tutoriales.Find(id);
            tutoriales.Estado = false;
            db.SaveChanges();
            ViewBag.EliminarTutorial = "ok";
            if (tutoriales == null)
            {

                return HttpNotFound();
            }
            return RedirectToAction("Index", "tutoriales");
            //return View(tutoriales);
        }

     

        [CustomAuthorize]
        public ActionResult EncuestaClima()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

intra/Views/Tutoriales/Create.cshtml
@model intra.Tutoriales

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/intraMaster.cshtml";
}
<link href="~/Content/css/jquery-te-1.4.0.css" rel="stylesheet" />
<script src="~/scripts/jquery-te-1.4.0.min.js"></script>
<script src="~/scripts/jquery-te-1.4.0.js"></script>
<script src="~/scripts/jquery.validate.js"></script>
<link href="~/CSS/sweetalert2.css" rel="stylesheet" />
<script src="~/scripts/sweetalert2.js"></script>

@if(ViewBag.Tutoriales != null)
{
    <script>
        swal('Error',
            'Debe Seleccionar un video',
            'error');
    </script>
}

@using (Html.BeginForm("create", "Tutoriales", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()


    <section class="row">
        <div class="col-md-6">
            <h2 class="h2_title_page">Tutoriales</h2>
            <hr class="hr2" />
        </div>
        <div class="col-md-6">
            <div class="pull-right alejar_top btn-group botones">
                <input type="submit" value="Subir tutorial" class="btn button_white" />
                   @Html.ActionLink("Volver", "/Index", null, new { @class= "btn button_white" })

            </div>

        </div>
    </section>

    <div class="row">
           <div class="col-lg-6">
               <label>Tutorial</label>
                <div>
                    <input type="text" name="Tutorial" value="" class="form-control" />
                </div>
            </div>

            <div class="col-lg-6">
                <label>Cargar Video</label>
                <div>
                    <input type="file" name="file" class="file" />
                </div>
            </div>
        <div class="form-group" hidden="hidden">
                @Html.Label("Portada", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="portada" class="form-control" />
                </div>
            </div>
        

        </div>

}



<script>
	$('.jqte-test').jqte();

	// settings of status
	var jqteStatus = true;
	$(".status").click(function()
	{
		jqteStatus = jqteStatus ? false : true;
		$('.jqte-test').jqte({"status" : jqteStatus})
	});

</script>

<script>
$().ready(function() {
        // valida Formulario
        $("form").validate({
            rules: {
                Tutorial: "required",

                    },
            messages: {
                Tutorial: "El nombre es Requerido",
                      }
        })

});

</script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

intra/Views/Tutoriales/Delete.cshtml
@model intra.Tutoriales

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/intraMaster.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tutoriales</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TutorialNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TutorialNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TutorialUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TutorialUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

intra/Views/Tutoriales/Details.cshtml
@model intra.Tutoriales

@{
    ViewBag.Title = "Details";    
   Layout = "~/Views/intraMaster.cshtml";
}

<style>
    .noticias {
        margin-bottom: 15px;
    }
</style>


    <div class="row">
        <div class="col-lg-9">
            <h2 class="h2_title_page">@Html.DisplayFor(model => model.TutorialNombre)</h2>
        </div>
        <div class="col-lg-3">
            <div class="pull-right alejar_top">
                <span>
                    @Html.ActionLink("Salir", "Index", "home", null, new { @class = "btn button_white" })
                </span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <hr class="hr2" style="width: 100% !important;">
            <video controls poster="@Model.Portada" style="width:100% !important;">
                <source src="@Model.TutorialUrl" type="video/mp4" />
            </video>
        </div>
    </div>
   

intra/Views/Tutoriales/Edit.cshtml
@model intra.Tutoriales

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/intraMaster.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TutorialId)

    <section class="row">
        <div class="col-md-6">
            <h2 class="h2_title_page">Tutoriales</h2>
            <hr class="hr2" />
        </div>
        <div class="col-md-6">
            <div class="pull-right alejar_top btn-group botones">
                <input type="submit" value="Guardar" class="btn button_white" />
                @Html.ActionLink("Volver", "/Index", null, new { @class = "btn button_white" })

            </div>

        </div>
    </section>

    <div class="row">
      
        <div class="col-lg-4">
            <label>Nombre del Tutorial</label>
            <div>
                @Html.EditorFor(model => model.TutorialNombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TutorialNombre, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="col-lg-4" hidden="hidden">
            <label>Portada</label>
            <div>
                <input type="file" name="file" class="form-control" />
            </div>
        </div>

        <div class="col-lg-4">
            <label>Cargar Video</label>
            <div>
                <input type="file"  name="file" class="form-control" />
            </div>
        </div>
        <div class="col-lg-2">
            <label>Creado Por</label>
            <div>
                @Html.DisplayFor(model => model.TutorialUsuario)
            </div>
        </div>
        <div class="col-lg-2">
            <label>Fecha Creacion</label>
            <div>
                @Html.DisplayFor(model => model.FechaCreacion)
            </div>
        </div>

        @Html.HiddenFor(model => model.TutorialUsuario)
        @Html.HiddenFor(model => model.FechaCreacion)

        <div style="width:30%">
            Video Actual
            <video controls poster="@Model.Portada" style="height: 80vh !important;">
                <source src="@Model.TutorialUrl" type="video/mp4" />
            </video>
        </div>

    </div>
}

intra/Views/Tutoriales/EncuestaClima.cshtml
@{
    ViewBag.Title = "EncuestaClima";
    Layout = "~/Views/intraMaster.cshtml";
}

<style> 
       video {
        width: 100%;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 320px;
        background: #1f3075;
    }

    .pk_video {
     background-color: red !important; 

    </style> 
<h2>EncuestaClima</h2>
<div class="col-lg-8 centerHomeContent">

    <video style="border:#207a95 solid;"controls poster="~/Content/images/portada_solicitud_servicios_intranet.jpg">
        <source src="~/Content/videos/Encuesta Clima Laboral 2017.mp4" type="video/mp4">
        <source src="~/Content/videos/SolicituddeServicios-Intranet.mp4" type="video/webm">
    </video>
    </div>

intra/Views/Tutoriales/Index.cshtml
@model IEnumerable<intra.Tutoriales>

@using System.Globalization;

@*@model PagedList.IPagedList<intra.Tutorial>
    @using PagedList.Mvc;*@
@{
    ViewBag.Title = "Index";

    if (ViewBag.access == "public_user")
    {
        Layout = "~/Views/intraMasterPublic.cshtml";
    }
    else
    {
        Layout = "~/Views/intraMaster.cshtml";
    }
}
<script src="~/scripts/jquery.dataTables.min.js"></script>
<link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/scripts/dataTables.responsive.min.js"></script>
<link href="~/Content/css/responsive.dataTables.css" rel="stylesheet" />
<link href="~/CSS/sweetalert2.css" rel="stylesheet" />
<script src="~/scripts/sweetalert2.js"></script>
<style>
    table {
        max-width: 100% !important;
    }
</style>

@if(ViewBag.EliminarTutorial != null)
{
    <script>
        swal('Eliminado',
            'Datos eliminado Correctamente',
            'success')
    </script>
}
<section class="row">
    <div class="col-md-6">
        <h2 class="h2_title_page">Tutoriales</h2>
        <hr class="hr2" />
    </div>
@if (User.IsInRole("TUTORIALES(ADMIN)"))
{
    <div class="col-md-6">
        <div class="pull-right alejar_top btn-group botones">
            @Html.ActionLink("Crear Nuevo", "Create", null, new { @class = "btn button_white" })
        </div>

    </div>
}
</section>
<br />
<br />

<table id="tableGrid" class="table table-striped table-hover responsive display  no-wrap" width="100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Tutorial")
            </th>

            <th>
                @Html.DisplayName("Fecha Creacion")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var tutorial in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(tutorial.TutorialNombre ?? " ", "Details", new { id = tutorial.TutorialId })
                    @*@Html.DisplayFor(modelItem => item.TutorialNombre)*@
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.TutorialUsuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TutorialVideo)
                    </td>*@
                <td>
                    @tutorial.FechaCreacion.ToString("d MMMM yyyy", new CultureInfo("es-ES"))
                    @*@Html.DisplayFor(modelItem => item.FechaCreacion)*@
                </td>
             
                <td>
                    @Html.ActionLink("Ver", "Details", new { id = tutorial.TutorialId }, new { @class = "btn button_white" })
                   @if (User.IsInRole("TUTORIALES(ADMIN)"))
                    {
                    @Html.ActionLink("Actualizar", "Edit", new { id = tutorial.TutorialId },  new { @class = "btn button_white" }) 
                    @Html.ActionLink("Eliminar", "Delete", new { id = tutorial.TutorialId }, new { @class = "btn button_white" })
                   }
                </td>
               
            </tr>
        }

    </tbody>
</table>


<script>
    $(document).ready(function () {
        $('#tableGrid').DataTable({
            "language": {
                "processing": "...Procesando...",
                "lengthMenu": "Mostrar _MENU_ registros",
                "zeroRecords": "No se encontraron registros disponibles",
                "emptyTable": "No hay Datos Disponibles en esta Tabla",
                "info": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "infoFiltered": "(filtrado de un total de _MAX_ registros)",
                "infoPostFix": "",
                "search": "Buscar:",
                "url": "",
                "infoThousands": ",",
                "loadingRecords": "...Cargando...",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                },
                "aria": {
                    "sortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sortDescending": ": Activar para ordenar la columna de manera descendente"
                }

            },
            responsive: true

        });
    });

</script>

intra/Views/Tutoriales/vTutoriales.cshtml
@model IEnumerable<intra.Tutoriales>


 
<div class="col-lg-4 leftHomeContent">
    <div class="inicioTutoriales">
        <div class="arrow-rightWhite"></div><h3>Tutoriales</h3>
        <ul>
            @foreach (var item in Model.OrderByDescending(c => c.TutorialId).Take(4))
            {
                <li><a href="~/Tutoriales/Details?id=@item.TutorialId">@item.TutorialNombre</a></li>
            }
        </ul>
      

        @Html.ActionLink("+ Más", "Index", "Tutoriales", null, new { @class = "botonFlotante" })
    </div>

    @*<div class="col-lg-4 leftHomeContent">
            <div class="inicioDirectorio">
                <div class="arrow-rightWhiteDirectorio"></div>
                <h3>Directorio Departamental</h3>
                <ul>
                    <li>Crear y formatear tablas en excel</li>
                    <li>Configurar paginas para impresion</li>
                    <li>Solicitar servicios por la intranet</li>
                    <li>Consifurar Outlook en el celular</li>
                </ul>
                @Html.ActionLink("+ Más", "Create", null, new { @class = "botonFlotante" })
            </div>
        </div>
        <div class="col-lg-4 leftHomeContent">
            <div class="inicioPlantillas">
                <div class="arrow-rightt"></div> <h3>Plantillas</h3>
                <ul>
                    <li><i class="fa fa-file-word-o" aria-hidden="true" style="color:#2b5796"></i>Formato de Carta 8.5x11</li>
                    <li><i class="fa fa-file-powerpoint-o" aria-hidden="true" style="color:#d04727"></i>Presentación de Power Point</li>
                    <li><i class="fa fa-file-excel-o" aria-hidden="true" style="color:#207347"></i>Tablas de Excel</li>
                    <li><i class="fa fa-file-word-o" aria-hidden="true" style="color:#2b5796"></i>Diagramas de Visio</li>
                </ul>
                @Html.ActionLink("+ Más", "Create", null, new { @class = "botonFlotantePlantillas" })
            </div>
        </div>*@
</div>