intra/Controllers/SistemaRepatriados/ServiciosRepatriadosController.cs
using intra.Models.GestionHumana;
using intra.Models.SistemaRepatriados;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace intra.Controllers.SistemaRepatriados
{
    public class ServiciosRepatriadosController : Controller
    {
        private dbIntranet db = new dbIntranet();

        public ActionResult Lista()
        {
            ViewBag.layout = "~/Views/intraMaster.cshtml";
            ViewBag.crear = "si";

            return View(db.SSR_Servicios.Where(x => x.ServicioEstadoId == 1).ToList());
        }

        public ActionResult Solicitados()
        {
            string codigo = HttpContext.Session["empleadoId"].ToString();

            ViewBag.crear = "si";
            ViewBag.layout = "~/Views/intraMaster.cshtml";

            return View("Index", db.SSR_Servicios.Where(x => x.ServicioEstadoId == 1 && x.CodigoCreador == codigo).ToList());
        }

        public ActionResult SolicitadosPartial()
        {
            string codigo = HttpContext.Session["empleadoId"].ToString();
            var CantidadSolicitados = db.SSR_Servicios.Where(x => x.CodigoCreador == codigo && x.ServicioEstadoId == 1).ToList().Count();
            var cantidadAsignados = db.SSR_Servicios.Where(x => x.CodigoResponsable == codigo && x.ServicioEstadoId == 1).ToList().Count();
            Session["CantidadServicioSolicitadosRepatriados"] = CantidadSolicitados;
            Session["CantidadServicioAsignadosRepatriados"] = cantidadAsignados;
            PartialViewBag();
            return View("Solicitados");
        }

        public ActionResult Asignados()
        {
            string codigo = HttpContext.Session["empleadoId"].ToString();

            ViewBag.crear = "si";
            ViewBag.layout = "~/Views/intraMaster.cshtml";

            return View("Index", db.SSR_Servicios.Where(x => x.ServicioEstadoId == 1 && x.CodigoResponsable == codigo).ToList());
        }

        public ActionResult AsignadosPartial()
        {
            string codigo = HttpContext.Session["empleadoId"].ToString();
            var CantidadSolicitados = db.SSR_Servicios.Where(x => x.CodigoCreador == codigo && x.ServicioEstadoId == 1).ToList().Count();
            var cantidadAsignados = db.SSR_Servicios.Where(x => x.CodigoResponsable == codigo && x.ServicioEstadoId == 1).ToList().Count();
            Session["CantidadServicioSolicitadosRepatriados"] = CantidadSolicitados;
            Session["CantidadServicioAsignadosRepatriados"] = cantidadAsignados;
            PartialViewBag();
            return View("Asignados");
        }

        public ActionResult Crear()
        {
            ViewBag.layout = "~/Views/intraMaster.cshtml";
            getSelectLists();
            return View();
        }

        public ActionResult CrearPartial()
        {
            ViewBag.ServicioTipoId = new SelectList(db.SSR_ServiciosTipos.Where(s => s.Estado == true), "ServicioTipoId", "Descripcion");
            ViewBag.IdRepatriados = new SelectList(new List<SSR_Servicios>(), "RepatriadoId", "NombreCompleto");
            ViewBag.InstitucionId = new SelectList(db.SSR_Instituciones.Where(i => i.Estado == true), "InstitucionId", "Descripcion");
            return View("Crear");
        }

        [HttpPost]
        public JsonResult CrearModal(SSR_Servicios ssr_servicios)
        {
            List<string> Errores = new List<string>();

            ssr_servicios.RepatriadoId = int.Parse(Request.Form["IdRepatriados"].ToString());
            ssr_servicios.ServicioTipoId = int.Parse(Request.Form["ServicioTipoId"].ToString());
            ssr_servicios.InstitucionId = int.Parse(Request.Form["InstitucionId"].ToString());
            ssr_servicios.Notas = Request.Form["Notas"].ToString();

            if (ssr_servicios.ServicioTipoId == null || ssr_servicios.ServicioTipoId == 0) Errores.Add("Tipo de servicio inválido");
            if (ssr_servicios.RepatriadoId == 0) Errores.Add("Repatriado inválido");
            if (ssr_servicios.InstitucionId == 0) Errores.Add("Institución inválido");
            if (string.IsNullOrWhiteSpace(ssr_servicios.Notas)) Errores.Add("Debe ingresar una nota del servicio que desea realizar");

            if (Errores.Count == 0)
            {

                ssr_servicios.FechaCreacion = DateTime.Now;
                ssr_servicios.FechaFin = DateTime.Now.AddDays(1);
                ssr_servicios.ServicioEstadoId = 1;
                ssr_servicios.UsuarioCreador = HttpContext.Session["usuario"].ToString();
                ssr_servicios.CodigoCreador = HttpContext.Session["empleadoId"].ToString();

                var resposable = db.SSR_ResponsableRepatriados.FirstOrDefault();

                ssr_servicios.UsuarioResponsable = resposable.UsuarioResponsable;
                ssr_servicios.CodigoResponsable = resposable.CodigoResponsable;

                try
                {
                    db.SSR_Servicios.Add(ssr_servicios);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    return Json("Error");
                }

                try
                {
                    EnviarCorreoServicioRepatriado(new string[] { resposable.CorreoResponsable, HttpContext.Session["correo"].ToString() }, "USTED HA RECIBIDO UN MENSAJE DE SERVICIOS REPATRIADOS",
                        Descripcion("SERVICIO REPATRIADOS", " " + HttpContext.Session["departamento"].ToString().ToUpper(), HttpContext.Session["nombre"].ToString().ToUpper(),
                        ssr_servicios.Notas, ssr_servicios.ServicioId, " nombre del servicio repatriados"));
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    return Json("ErrorDeCorreo");
                }

                return Json("Guardado");

            }

            return Json(Errores);
        }

        [HttpPost]
        public JsonResult Crear(SSR_Servicios ssr_servicios)
        {
            List<string> Errores = new List<string>();

            ssr_servicios.RepatriadoId = int.Parse(Request.Form["IdRepatriados"].ToString());

            if (ssr_servicios.ServicioTipoId == null || ssr_servicios.ServicioTipoId == 0) Errores.Add("Tipo de servicio inválido");
            if (ssr_servicios.RepatriadoId == 0) Errores.Add("Repatriado inválido");
            if (ssr_servicios.InstitucionId == 0) Errores.Add("Institución inválido");
            if (string.IsNullOrWhiteSpace(ssr_servicios.Notas)) Errores.Add("Debe ingresar una nota del servicio que desea realizar");

            if (Errores.Count == 0)
            {

                ssr_servicios.FechaCreacion = DateTime.Now;
                ssr_servicios.FechaFin = DateTime.Now.AddDays(1);
                ssr_servicios.ServicioEstadoId = 1;
                ssr_servicios.UsuarioCreador = HttpContext.Session["usuario"].ToString();
                ssr_servicios.CodigoCreador = HttpContext.Session["empleadoId"].ToString();

                var resposable = db.SSR_ResponsableRepatriados.FirstOrDefault();

                ssr_servicios.UsuarioResponsable = resposable.UsuarioResponsable;
                ssr_servicios.CodigoResponsable = resposable.CodigoResponsable;

                try
                {
                    db.SSR_Servicios.Add(ssr_servicios);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    return Json("Error");
                }

                try
                {
                    EnviarCorreoServicioRepatriado(new string[] { resposable.CorreoResponsable, HttpContext.Session["correo"].ToString() }, "USTED HA RECIBIDO UN MENSAJE DE SERVICIOS REPATRIADOS",
                        Descripcion("SERVICIO REPATRIADOS", " " + HttpContext.Session["departamento"].ToString().ToUpper(), HttpContext.Session["nombre"].ToString().ToUpper(),
                        ssr_servicios.Notas, ssr_servicios.ServicioId, " nombre del servicio repatriados"));
                }
                catch (Exception ex)
                {
                    ex.ToString();
                    return Json("ErrorDeCorreo");
                }

                return Json("Guardado");

            }

            return Json(Errores);
        }

        public ActionResult RegistroServicio(int id)
        {
            SSR_Servicios servicio = db.SSR_Servicios.Find(id);

            if (servicio == null) return HttpNotFound();

            if (User.IsInRole("SRA"))
            {

                getSelectLists(servicio.ServicioTipoId.GetValueOrDefault(), servicio.RepatriadoId, servicio.InstitucionId);

                ViewBag.CodigoResponsable = new SelectList(db.VISTA_EMPLEADOS.Where(x => x.cargoid == "517"), "Empleadoid", "Nombre", servicio.CodigoResponsable);
            }
            //else if (User.IsInRole("SRAC")) { }

            ViewBag.ServicioEstadoId = new SelectList(db.SSR_ServiciosEstados.Where(x=>x.ServicioEstadoId != 4), "ServicioEstadoId", "Descripcion", servicio.ServicioEstadoId);

            return View(servicio);
        }

        public JsonResult CargarServicioRepatriado(int id)
        {
            SSR_Servicios servicio = db.SSR_Servicios.Find(id);

            return Json(servicio);
        }

        [HttpPost]
        public JsonResult RegistroServicio(SSR_Servicios servicio)
        {
            //getSelectLists();
            SSR_Servicios ssr_servicios = db.SSR_Servicios.Find(servicio.ServicioId);

            if (User.IsInRole("SRA"))
            {

                if (ssr_servicios.CodigoResponsable != servicio.CodigoResponsable) ActualizarResponsable(ssr_servicios, servicio);

intra/Views/ServiciosRepatriados/Asignados.cshtml
@{
        ViewBag.Title = "Servicios Repatriados";
        Layout = ViewBag.layout;
    }

    @*@Styles.Render("~/datatables/css")*@

    @if (ViewBag.crear != null)
    {

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Crear nuevo servicio", "Crear")
</p>*@

    }
   

<link href="~/CSS/sweetalert2.css" rel="stylesheet" />
<script src="~/scripts/sweetalert2.min.js"></script>

<section class="row br-head-title">
    <div class="col-md-8">
        <h2 class="h2_title_page">Servicio de Repatriados Asignados</h2>
        <hr class="hr2" />
    </div>
    <div class="col-md-4">
        <div class="pull-right alejar_top btn-group botones">
            <a class="btn button_white AparecerFiltroAsigandos"><i class="fa fa-filter alejar_icono"></i>Filtro</a>
        </div>
    </div>
</section>

<div class="row br-solicitados-head accordion-filtro accordion-asignados">
    <div class="col-md-10 content">
        <div class="<!-- pull-right --> cont">
            <div style="float:left; margin-left:2px" class="br-item">
                <label>Filtrar Por:</label>
                <select class="form-control OpcionesAsnd">
                    <option>Seleccione</option>
                    <option value="1">Institución</option>
                    <option value="2">Tipo de Servicio</option>
                    <option value="3">Fecha</option>
                </select>
            </div>
            <div style="float:left; margin-left:2px">
                <div style="float:left;margin-left:2px; display:none" class="br-item institucion_div_Asnd">
                    <label>Institución:</label>
                    <div>
                        @Html.DropDownList("institucionAsnd", (SelectList)ViewBag.institucion, "Seleccione", new { @class = "form-control" })
                    </div>
                </div>
                <div style="float:left;margin-left:2px; display:none" class="br-item tipoServicio_div_Asnd">
                    <label>Tipo de Servicio:</label>
                    <div>
                        @Html.DropDownList("tipoServicioAsnd", (SelectList)ViewBag.tipoServicio, "Seleccione", new { @class = "form-control" })
                    </div>
                </div>
                <div style="float:left;margin-left:2px;display:none" class="Fechas_div_Asnd">
                    <div style="float:left;margin-left:2px">
                        <label>Fecha Inicial:</label>
                        @Html.TextBox("fechainicioAsnd", DateTime.Now.ToString("dd/MM/yyyy"), new { @class = "date-picker form-control date-picker-filtro" })
                    </div>
                    <div style="float:left;margin-left:6px">
                        <label>Fecha Final:</label>
                        @Html.TextBox("fechafinalAsnd", DateTime.Now.ToString("dd/MM/yyyy"), new { @class = "date-picker form-control date-picker-filtro" })
                    </div>
                </div>
            </div>
            <div style="float:left; margin-left:2px" class="br-item">
                <div style="float:left;margin-left:2px">

                    <label>Estados:</label>
                    @Html.DropDownList("estadosAsnd", (SelectList)ViewBag.estados, "Todos", new { @class = "form-control" })
                </div>
                <div style="float:left;">
                    <button style="margin-top: 31px;margin-left: 10px;" type="submit" class="button_white ConsultarAsnd"><i class="fa fa-search alejar_icono"></i>Consultar</button>
                </div>

            </div>

        </div>
    </div>
</div>


<table class="table display responsive nowrap tableGrid tblAsignados br-table-serv-rep" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Repatriado</th>
            <th>Tipo de servicio</th>
            <th>Estado de servicio</th>
            <th class="none">Fecha de solicitud</th>
            <th class="none">Nota</th>
        </tr>
    </thead>
    <tbody></tbody>

</table>
@*
    <div class="modal fade ServicioModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                @Html.Action("CrearPartial", "ServiciosRepatriados")
            </div>
        </div>
    </div>

    <div class="modal fade ServicioModal2" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="crear_servicio">

                    <section class="row">
                        <div class="col-md-4">
                            <h2 class="h2_title_page">Crear Servicio de Repatriados</h2>
                            <hr class="hr2" />
                        </div>
                        <div class="col-md-8">
                            <div class="pull-right alejar_top btn-group botones">

                                <a *id="CrearServicio" * @ class=" btn button_white"><i class="fa fa-save alejar_icono"></i>Guardar</a>
                                <a @*href="@Url.Action(" Index")" * @ class="btn button_white pruebamodal2"><i class="fa fa-chevron-left alejar_icono"></i>Volver</a>
                                @*<button type="button" value="volver" class="btn button_white" onclick="window.history.back();"><i class="fa fa-chevron-left alejar_icono"></i>Volver</button> * @
                            </div>

                        </div>
                    </section>
                    <div class="container">

                        <div class="row">

                            <div class="col-lg-2">
                                <label>Tipo de Servicio</label>
                                <select class="form-control"></select>
                            </div>

                            <div class="col-lg-2">
                                <label>Persona Repatriada</label>
                                <select class="form-control chosen"></select>
                            </div>

                            <div class="col-lg-2">
                                <label>Institución Responsable</label>
                                <select class="form-control"></select>
                            </div>

                        </div>


                        <div class="row">
                            <div class="col-lg-6">
                                <label>Notas del servicio</label>
                                <textarea id="Notas" name="Notas" rows="6" cols="50"></textarea>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>


                                       Scripts.Render("~/datatables/js")*@
@*<script>
            //$('.tableGrid').DataTable().order([[0, 'desc']]).draw();


            $('.div_oculto').on('click', function () {
                $('.containermodal1').toggle();
                $('.containermodal2').toggle();
            });

            $('.CrearServicioModal').on('click', function () {
                $('.ServicioModal').modal();
            });

            $('.pruebamodal').on('click', function () {
                $('.ServicioModal').modal('hide');
                $('.ServicioModal2').modal();
            });

            $('.pruebamodal2').on('click', function () {
                $('.ServicioModal2').modal('hide');
                $('.ServicioModal').modal();
            });

</script>*@
<script src="~/scripts/create_serviciorepatriados.js"></script>

intra/Views/ServiciosRepatriados/Asignadosss.cshtml
@*{
        ViewBag.Title = "Servicios Repatriados";
        Layout = ViewBag.layout;
    }

    @Styles.Render("~/datatables/css")

    @if (ViewBag.crear != null)
    {

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo servicio", "Crear")
</p>

    }
    @*@

<link href="~/CSS/sweetalert2.css" rel="stylesheet" />
<script src="~/scripts/sweetalert2.min.js"></script>


<section class="row br-head-title">
    <div class="col-md-8">
        <h2 class="h2_title_page">Servicio de Repatriados Asignados</h2>
        <hr class="hr2" />
    </div>
    <div class="col-md-4">
        <div class="pull-right alejar_top btn-group botones">
            <a class="btn button_white AparecerFiltroAsigandos"><i class="fa fa-filter alejar_icono"></i>Filtro</a>
        </div>
    </div>
</section>

<div class="row br-solicitados-head accordion-filtro accordion-asignados">
    <div class="col-md-10 content">
        <div class="<!-- pull-right --> cont">
            <div style="float:left; margin-left:2px" class="br-item">
                <label>Filtrar Por:</label>
                <select class="form-control OpcionesAsnd">
                    <option>Seleccione</option>
                    <option value="1">Institución</option>
                    <option value="2">Tipo de Servicio</option>
                    <option value="3">Fecha</option>
                </select>
            </div>
            <div style="float:left; margin-left:2px">
                <div style="float:left;margin-left:2px; display:none" class="br-item institucion_div_Asnd">
                    <label>Institución:</label>
                    <div>
                        @Html.DropDownList("institucionAsnd", (SelectList)ViewBag.institucion, "Seleccione", new { @class = "form-control" })
                    </div>
                </div>
                <div style="float:left;margin-left:2px; display:none" class="br-item tipoServicio_div_Asnd">
                    <label>Tipo de Servicio:</label>
                    <div>
                        @Html.DropDownList("tipoServicioAsnd", (SelectList)ViewBag.tipoServicio, "Seleccione", new { @class = "form-control" })
                    </div>
                </div>
                <div style="float:left;margin-left:2px;display:none" class="Fechas_div_Asnd">
                    <div style="float:left;margin-left:2px">
                        <label>Fecha Inicial:</label>
                        @Html.TextBox("fechainicioAsnd", DateTime.Now.ToString("dd/MM/yyyy"), new { @class = "date-picker form-control date-picker-filtro" })
                    </div>
                    <div style="float:left;margin-left:6px">
                        <label>Fecha Final:</label>
                        @Html.TextBox("fechafinalAsnd", DateTime.Now.ToString("dd/MM/yyyy"), new { @class = "date-picker form-control date-picker-filtro" })
                    </div>
                </div>
            </div>
            <div style="float:left; margin-left:2px" class="br-item">
                <div style="float:left;margin-left:2px">

                    <label>Estados:</label>
                    @Html.DropDownList("estadosAsnd", (SelectList)ViewBag.estados, "Todos", new { @class = "form-control" })
                </div>
                <div style="float:left;">
                    <button style="margin-top: 31px;margin-left: 10px;" type="submit" class="button_white ConsultarAsnd"><i class="fa fa-search alejar_icono"></i>Consultar</button>
                </div>

            </div>

        </div>
    </div>
</div>


<table class="table display responsive nowrap tableGrid tblAsignados br-table-serv-rep" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Repatriado</th>
            <th>Tipo de servicio</th>
            <th>Estado de servicio</th>
            <th class="none">Fecha de solicitud</th>
            <th class="none">Nota</th>
        </tr>
    </thead>
    <tbody></tbody>

</table>
@*
<div class="modal fade ServicioModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @Html.Action("CrearPartial", "ServiciosRepatriados")
        </div>
    </div>
</div>

<div class="modal fade ServicioModal2" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="crear_servicio">

                <section class="row">
                    <div class="col-md-4">
                        <h2 class="h2_title_page">Crear Servicio de Repatriados</h2>
                        <hr class="hr2" />
                    </div>
                    <div class="col-md-8">
                        <div class="pull-right alejar_top btn-group botones">

                            <a *id="CrearServicio" * @ class=" btn button_white"><i class="fa fa-save alejar_icono"></i>Guardar</a>
                            <a @*href="@Url.Action(" Index")" * @ class="btn button_white pruebamodal2"><i class="fa fa-chevron-left alejar_icono"></i>Volver</a>
                            @*<button type="button" value="volver" class="btn button_white" onclick="window.history.back();"><i class="fa fa-chevron-left alejar_icono"></i>Volver</button> * @
                        </div>

                    </div>
                </section>
                <div class="container">

                    <div class="row">

                        <div class="col-lg-2">
                            <label>Tipo de Servicio</label>
                            <select class="form-control"></select>
                        </div>

                        <div class="col-lg-2">
                            <label>Persona Repatriada</label>
                            <select class="form-control chosen"></select>
                        </div>

                        <div class="col-lg-2">
                            <label>Institución Responsable</label>
                            <select class="form-control"></select>
                        </div>

                    </div>


                    <div class="row">
                        <div class="col-lg-6">
                            <label>Notas del servicio</label>
                            <textarea id="Notas" name="Notas" rows="6" cols="50"></textarea>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>


                                   Scripts.Render("~/datatables/js")
<script>
            $('.tableGrid').DataTable().order([[0, 'desc']]).draw();


            $('.div_oculto').on('click', function () {
                $('.containermodal1').toggle();
                $('.containermodal2').toggle();
            });

            $('.CrearServicioModal').on('click', function () {
                $('.ServicioModal').modal();
            });

            $('.pruebamodal').on('click', function () {
                $('.ServicioModal').modal('hide');
                $('.ServicioModal2').modal();
            });

            $('.pruebamodal2').on('click', function () {
                $('.ServicioModal2').modal('hide');
                $('.ServicioModal').modal();
            });

</script>*@
<script src="~/scripts/create_serviciorepatriados.js"></script>

intra/Views/ServiciosRepatriados/Crear.cshtml
@model intra.Models.SistemaRepatriados.SSR_Servicios

@{
    ViewBag.Title = null;
    Layout = ViewBag.layout;
}

<link href="~/Content/css/textext/textext.core.css" rel="stylesheet" />
<link href="~/Content/css/textext/textext.plugin.autocomplete.css" rel="stylesheet" />
<link href="~/Content/css/textext/textext.plugin.tags.css" rel="stylesheet" />
<script src="~/Content/js/textext/textext.core.js"></script>
<script src="~/Content/js/textext/textext.plugin.autocomplete.js"></script>
<script src="~/Content/js/textext/textext.plugin.filter.js"></script>
<script src="~/Content/js/textext/textext.plugin.tags.js"></script>

<style>

    .swal-li {
        text-align: left;
    }

    .text-position-below {
        top: 21px !important;
        width: 100px;
    }

    #IdRepatriados_input {
        width: 100px;
    }

</style>


<form id="crear_servicio" method="post" action="">

    <section class="row br-head-title">
        <div class="col-md-6">
            <h2 class="h2_title_page">Crear Servicio de Repatriados</h2>
            <hr class="hr2" />
        </div>
        <div class="col-md-6">
            <div class="pull-right alejar_top btn-group botones">
                <button type="button" class="btn button_white " onclick="SaveServicio()"><i class="fa fa-save alejar_icono"></i>Guardar</button>
                <a class="btn button_white CerrarModal"><i class="fa fa-times-circle alejar_icono"></i>Cerrar</a>
            </div>

        </div>
    </section>

    <div class="container containermodal2">

        <div class="row">

            <div class="col-lg-2">
                <label>Tipo de Servicio</label>
                @Html.DropDownList("ServicioTipoId", null, "SELECCIONE EL TIPO SERVICIO", new { @class = "form-control" })
            </div>

            <div class="col-lg-2">
                <label>Persona Repatriada</label>

                @*<input type="hidden" id="IdRepatriados" />
                <input id="IdRepatriados_input" />*@

                @Html.DropDownList("IdRepatriados", null, "SELECCIONE LA PERSONA REPATRIADA", new { @class = "form-control chosen" })
            </div>

            <div class="col-lg-2">
                <label>Institución Responsable</label>
                @Html.DropDownList("InstitucionId", null, "SELECCIONE LA INSTITUCIÓN", new { @class = "form-control" })
            </div>

        </div>


        <div class="row">
            <div class="col-lg-6">
                <label>Notas del servicio</label>
                <textarea id="Notas" name="Notas" rows="6" cols="50"></textarea>
            </div>
        </div>

    </div>
</form>

<script src="~/scripts/create_serviciorepatriados.js"></script>

intra/Views/ServiciosRepatriados/Lista.cshtml
@model IEnumerable<intra.Models.SistemaRepatriados.SSR_Servicios>

@{
    ViewBag.Title = "Servicios Repatriados";
    Layout = "~/Views/intraMaster.cshtml";
}

@Styles.Render("~/datatables/css")

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo servicio", "Crear")
</p>
<table class="table display responsive nowrap tablagrid" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>#</th>
            <th>Repatriado</th>
            <th>Tipo de servicio</th>
            <th>Estado de servicio</th>
            <th class="none">Fecha de solicitud</th>
            <th class="none">Nota</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.ServicioId
                </td>
                <td>
                    @item.SSR_Repatriados.NombreCompleto
                </td>
                <td>
                    @item.SSR_ServiciosTipos.Descripcion
                </td>
                <td>
                    
                    @Html.ActionLink(item.SSR_ServiciosEstados.Descripcion, "RegistroServicio","ServiciosRepatriados", new { id = item.ServicioId }, new { @class = "estatus estatus_rechazado" })
                </td>
                <td>
                    @item.FechaCreacion.GetValueOrDefault().ToString("dd/MM/yyyy")
                </td>
                <td>
                    @item.Notas
                </td>
            </tr>
        }

    </tbody>


</table>
@Scripts.Render("~/datatables/js")

<script>
    $('.tablagrid').DataTable().order([[0, 'desc']]).draw();
</script>